version: '3'
services:
  server:
    build: ./server
    container_name: node_api
    ports:
      - '5000:8000'
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/app
    networks:
      - my_network

  client:
    build: ./client
    container_name: Awesome-Todo
    ports:
      - '3000:3000'
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
    networks:
      - my_network  
      
  database:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_URI: mongodb+srv://lebon2024:2024@testtask.zvvit1s.mongodb.net/?retryWrites=true&w=majority&appName=testtask
    networks:
      - my_network 

volumes:
  mongodb_data_container:

networks:
  my_network:
