# Utiliser une image officielle Node.js comme image parente
FROM node:18.15.0

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package.json package.json

# Installer les dépendances du projet
RUN npm install

# Copier les fichiers du projet dans le conteneur
COPY . .

# Exposer le port sur lequel l'application s'exécutera 
EXPOSE 5000

# Exécuter l'application 
CMD ["node", "index.js"]
